## Bases de datos
- Operaciones entre variables
- **Operaciones entre variables**
- *Operaciones entre variables*
- ***Operaciones entre variables***
- <u>Operaciones entre variables</u>

#### 1. Manejo de Markdown

#### 2. Instalación de librerías para leer bases de datos

In [2]:
# Importamos las librerías necesarias
#pip install pandas #(para acceder y leer bases de datos)
#pip install numpy #(operaciones y arreglos númericos)
import pandas as pd # Abre las bases de datos
import numpy as np # Para operaciones númericas

#### 3. Cargar Base de Datos

In [3]:
data=pd.read_csv("BankChurners.csv") # Cargamos la base de datos

#### 4. Visualizar la base de Datos

In [4]:
data.head() # Mostramos las primeras filas de la base de datos

,CLIENTNUM,Attrition_Flag,Customer_Age,Gender,Dependent_count,Education_Level,Marital_Status,Income_Category,Card_Category,Months_on_book,...,Credit_Limit,Total_Revolving_Bal,Avg_Open_To_Buy,Total_Amt_Chng_Q4_Q1,Total_Trans_Amt,Total_Trans_Ct,Total_Ct_Chng_Q4_Q1,Avg_Utilization_Ratio,Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_1,Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_2
0,768805383,Existing Customer,45,M,3,High School,Married,$60K - $80K,Blue,39,...,12691.0,777,11914.0,1.335,1144,42,1.625,0.061,0.000093,0.99991
1,818770008,Existing Customer,49,F,5,Graduate,Single,Less than $40K,Blue,44,...,8256.0,864,7392.0,1.541,1291,33,3.714,0.105,0.000057,0.99994
2,713982108,Existing Customer,51,M,3,Graduate,Married,$80K - $120K,Blue,36,...,3418.0,0,3418.0,2.594,1887,20,2.333,0.000,0.000021,0.99998
3,769911858,Existing Customer,40,F,4,High School,Unknown,Less than $40K,Blue,34,...,3313.0,2517,796.0,1.405,1171,20,2.333,0.760,0.000134,0.99987
4,709106358,Existing Customer,40,M,3,Uneducated,Married,$60K - $80K,Blue,21,...,4716.0,0,4716.0,2.175,816,28,2.500,0.000,0.000022,0.99998

In [5]:
data.tail() # Mostramos las últimas filas de la base de datos

,CLIENTNUM,Attrition_Flag,Customer_Age,Gender,Dependent_count,Education_Level,Marital_Status,Income_Category,Card_Category,Months_on_book,...,Credit_Limit,Total_Revolving_Bal,Avg_Open_To_Buy,Total_Amt_Chng_Q4_Q1,Total_Trans_Amt,Total_Trans_Ct,Total_Ct_Chng_Q4_Q1,Avg_Utilization_Ratio,Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_1,Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_2
10122,772366833,Existing Customer,50,M,2,Graduate,Single,$40K - $60K,Blue,40,...,4003.0,1851,2152.0,0.703,15476,117,0.857,0.462,0.000191,0.999810
10123,710638233,Attrited Customer,41,M,2,Unknown,Divorced,$40K - $60K,Blue,25,...,4277.0,2186,2091.0,0.804,8764,69,0.683,0.511,0.995270,0.004729
10124,716506083,Attrited Customer,44,F,1,High School,Married,Less than $40K,Blue,36,...,5409.0,0,5409.0,0.819,10291,60,0.818,0.000,0.997880,0.002118
10125,717406983,Attrited Customer,30,M,2,Graduate,Unknown,$40K - $60K,Blue,36,...,5281.0,0,5281.0,0.535,8395,62,0.722,0.000,0.996710,0.003294
10126,714337233,Attrited Customer,43,F,2,Graduate,Married,Less than $40K,Silver,25,...,10388.0,1961,8427.0,0.703,10294,61,0.649,0.189,0.996620,0.003377

#### 5. Información de la base de Datos
- Información de la base de datos
- Información de una observación particular
- Observación con el valor máx. y mín. de una variable 
- Conteo de observaciones por variable 
- Valor únicos por variable

In [6]:
data.info() # Información general de la base de datos

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10127 entries, 0 to 10126
Data columns (total 23 columns):
 #   Column                                                                                                                              Non-Null Count  Dtype
---  ------                                                                                                                              --------------  -----
 0   CLIENTNUM                                                                                                                           10127 non-null  int64
 1   Attrition_Flag                                                                                                                      10127 non-null  object
 2   Customer_Age                                                                                                                        10127 non-null  int64
 3   Gender                                                                                                                              10127 non-null  object
 4   Dependent_count                                                                                                                     10127 non-null  int64
 5   Education_Level                                                                                                                     10127 non-null  object
 6   Marital_Status                                                                                                                      10127 non-null  object
 7   Income_Category                                                                                                                     10127 non-null  object
 8   Card_Category                                                                                                                       10127 non-null  object
 9   Months_on_book                                                                                                                      10127 non-null  int64
 10  Total_Relationship_Count                                                                                                            10127 non-null  int64
 11  Months_Inactive_12_mon                                                                                                              10127 non-null  int64
 12  Contacts_Count_12_mon                                                                                                               10127 non-null  int64
 13  Credit_Limit                                                                                                                        10127 non-null  float64
 14  Total_Revolving_Bal                                                                                                                 10127 non-null  int64
 15  Avg_Open_To_Buy                                                                                                                     10127 non-null  float64
 16  Total_Amt_Chng_Q4_Q1                                                                                                                10127 non-null  float64
 17  Total_Trans_Amt                                                                                                                     10127 non-null  int64
 18  Total_Trans_Ct                                                                                                                      10127 non-null  int64
 19  Total_Ct_Chng_Q4_Q1                                                                                                                 10127 non-null  float64
 20  Avg_Utilization_Ratio                                                                                                               10127 non-null  float64
 21  Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_1  10127 non-null  float64
 22  Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_2  10127 non-null  float64
dtypes: float64(7), int64(10), object(6)
memory usage: 1.8+ MB

In [7]:
# Quiero ver la información de la fila 23
data.iloc[22]

CLIENTNUM                                                                                                                                     784725333
Attrition_Flag                                                                                                                        Existing Customer
Customer_Age                                                                                                                                         41
Gender                                                                                                                                                M
Dependent_count                                                                                                                                       3
Education_Level                                                                                                                             High School
Marital_Status                                                                                                                                  Married
Income_Category                                                                                                                             $40K - $60K
Card_Category                                                                                                                                      Blue
Months_on_book                                                                                                                                       33
Total_Relationship_Count                                                                                                                              4
Months_Inactive_12_mon                                                                                                                                2
Contacts_Count_12_mon                                                                                                                                 1
Credit_Limit                                                                                                                                     4470.0
Total_Revolving_Bal                                                                                                                                 680
Avg_Open_To_Buy                                                                                                                                  3790.0
Total_Amt_Chng_Q4_Q1                                                                                                                              1.608
Total_Trans_Amt                                                                                                                                     931
Total_Trans_Ct                                                                                                                                       18
Total_Ct_Chng_Q4_Q1                                                                                                                               1.571
Avg_Utilization_Ratio                                                                                                                             0.152
Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_1             0.000069
Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_2              0.99993
Name: 22, dtype: object

In [8]:
# Quiero ver la edad del cliente en la observación 25
data.iloc[24]["Customer_Age"]

np.int64(54)

In [9]:
# Quisiera saber la observación con customer_age maximo 
data.loc[data["Customer_Age"].idxmax()]
# en donde dice data.loc le quitas el 'i' antes de loc para que no sea index

CLIENTNUM                                                                                                                                     715952883
Attrition_Flag                                                                                                                        Existing Customer
Customer_Age                                                                                                                                         73
Gender                                                                                                                                                M
Dependent_count                                                                                                                                       0
Education_Level                                                                                                                             High School
Marital_Status                                                                                                                                  Married
Income_Category                                                                                                                             $40K - $60K
Card_Category                                                                                                                                      Blue
Months_on_book                                                                                                                                       36
Total_Relationship_Count                                                                                                                              5
Months_Inactive_12_mon                                                                                                                                3
Contacts_Count_12_mon                                                                                                                                 2
Credit_Limit                                                                                                                                     4469.0
Total_Revolving_Bal                                                                                                                                1125
Avg_Open_To_Buy                                                                                                                                  3344.0
Total_Amt_Chng_Q4_Q1                                                                                                                              1.363
Total_Trans_Amt                                                                                                                                    1765
Total_Trans_Ct                                                                                                                                       34
Total_Ct_Chng_Q4_Q1                                                                                                                               1.615
Avg_Utilization_Ratio                                                                                                                             0.252
Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_1              0.00015
Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_2              0.99985
Name: 251, dtype: object

In [10]:
# Contento de valores unicos education_level
data['Education_Level'].value_counts()

Education_Level
Graduate         3128
High School      2013
Unknown          1519
Uneducated       1487
College          1013
Post-Graduate     516
Doctorate         451
Name: count, dtype: int64

In [11]:
# Numero de diferentes valores en la columna Education_Level
data['Education_Level'].nunique()

7

#### 6. Manipulación básica de una base de datos
- Borrar variables
- Borrar observaciones
- Borrar missing values
- Cambiar nombre de variables
- Agregar columna
- Operaciones básicas entre variables

In [25]:
# Eliminar columnas de la base de datos
datos2=data.drop(["Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_1","Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_2"], axis=1)

#axis=1 es para decir que son columnas y no filas

# Eliminar columnas por número de columna 
datos3=data.drop(data.columns[0:2],axis=1) #borra de 0 a 2
datos3=data.drop(data.columns[[0,2]],axis=1) #borra o y 2
datos3=data.drop(data.columns[0],axis="columns") #borra solo 0

In [ ]:
datos2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10127 entries, 0 to 10126
Data columns (total 21 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   CLIENTNUM                 10127 non-null  int64
 1   Attrition_Flag            10127 non-null  object
 2   Customer_Age              10127 non-null  int64
 3   Gender                    10127 non-null  object
 4   Dependent_count           10127 non-null  int64
 5   Education_Level           10127 non-null  object
 6   Marital_Status            10127 non-null  object
 7   Income_Category           10127 non-null  object
 8   Card_Category             10127 non-null  object
 9   Months_on_book            10127 non-null  int64
 10  Total_Relationship_Count  10127 non-null  int64
 11  Months_Inactive_12_mon    10127 non-null  int64
 12  Contacts_Count_12_mon     10127 non-null  int64
 13  Credit_Limit              10127 non-null  float64
 14  Total_Revolving_Bal       10127 non-null  int64
 15  Avg_Open_To_Buy           10127 non-null  float64
 16  Total_Amt_Chng_Q4_Q1      10127 non-null  float64
 17  Total_Trans_Amt           10127 non-null  int64
 18  Total_Trans_Ct            10127 non-null  int64
 19  Total_Ct_Chng_Q4_Q1       10127 non-null  float64
 20  Avg_Utilization_Ratio     10127 non-null  float64
dtypes: float64(5), int64(10), object(6)
memory usage: 1.6+ MB

In [ ]:
#Eliminar filas de la base de datos 

datos4=data.drop([0,1,2],axis=0)
datos4=data.drop(data.index[0:3],axis=0)
datos4=data.drop([4],axis="rows")

In [32]:
#Contar los valores nulos
print(datos2.isnull().sum())

#Eliminar valores nulos
data=datos2.dropna()

CLIENTNUM                   0
Attrition_Flag              0
Customer_Age                0
Gender                      0
Dependent_count             0
Education_Level             0
Marital_Status              0
Income_Category             0
Card_Category               0
Months_on_book              0
Total_Relationship_Count    0
Months_Inactive_12_mon      0
Contacts_Count_12_mon       0
Credit_Limit                0
Total_Revolving_Bal         0
Avg_Open_To_Buy             0
Total_Amt_Chng_Q4_Q1        0
Total_Trans_Amt             0
Total_Trans_Ct              0
Total_Ct_Chng_Q4_Q1         0
Avg_Utilization_Ratio       0
dtype: int64

In [44]:
# Cambiar nombre de la columna
data=data.rename(columns={"CLIENTNUM":"CLIENTE"})
data=data.rename(columns={"CLIENTNUM":"CLIENTE","Attrition_Flag":"Atricion","Gender":"Genero"})

In [45]:
#Agregar _ en lugar de espacios en blanco en columnas
data.columns=data.columns.str.replace(' ','_')
#data.columns=data.columns.str.replace('_',' ')
#data.columns=data.columns.str.replace(' ',' ')

In [51]:
#Agregar una columna igual a 1 si la columna gender es igual a 'M' y 0 si es 'F'
datos2['Genero']=datos4['Gender'].apply(lambda x: 1 if x=='M' else 0)

#Agregar una columna con el promedio de las columnas númericas
#datos2['Promedio']=datos4[numeric_columns].mean(axis=1)

# Asegurarse de que todas las columnas involucradas en operaciones aitméticas sean numéricas
numeric_columns=datos4.select_dtypes(include=['number']).columns
datos2['Promedio']=datos4[numeric_columns].mean(axis=1)

#Agregar una columna con la suma de las columnas númericas
datos2['Suma']=datos4[numeric_columns].sum(axis=1)

#Agregar una columna con la suma de dos columnas
datos2['Suma2']=datos4['Customer_Age']+datos4['Dependent_count']

#Agregar una columna con la resta de las columnas
datos2['Resta']=datos4['Customer_Age']-datos4['Dependent_count']

#Agregar una columna con la multiplicación de las columnas
datos2['Multiplicacion']=datos4['Customer_Age']*datos4['Dependent_count']

#Agregar una columna con la división de las columnas
datos2['Division']=datos4['Customer_Age']/datos4['Dependent_count']

#Mover la columna 'C' al inicio
columna=datos2.pop("Division") # Elimina la columna y la guarda en una variable
datos2.insert(0,"Division",columna) # Inserta la columna en la posición deseada

datos2.head()

,Division,CLIENTNUM,Attrition_Flag,Customer_Age,Gender,Dependent_count,Education_Level,Marital_Status,Income_Category,Card_Category,...,Total_Trans_Amt,Total_Trans_Ct,Total_Ct_Chng_Q4_Q1,Avg_Utilization_Ratio,Genero,Promedio,Suma,Suma2,Resta,Multiplicacion
0,15.0,768805383,Existing Customer,45,M,3,High School,Married,$60K - $80K,Blue,...,1144,42,1.625,0.061,1.0,4.522541e+07,7.688321e+08,48.0,42.0,135.0
1,9.8,818770008,Existing Customer,49,F,5,Graduate,Single,Less than $40K,Blue,...,1291,33,3.714,0.105,0.0,4.816400e+07,8.187880e+08,54.0,44.0,245.0
2,17.0,713982108,Existing Customer,51,M,3,Graduate,Married,$80K - $120K,Blue,...,1887,20,2.333,0.000,1.0,4.199947e+07,7.139910e+08,54.0,48.0,153.0
3,10.0,769911858,Existing Customer,40,F,4,High School,Unknown,Less than $40K,Blue,...,1171,20,2.333,0.760,0.0,4.528940e+07,7.699198e+08,44.0,36.0,160.0
4,NaN,709106358,Existing Customer,40,M,3,Uneducated,Married,$60K - $80K,Blue,...,816,28,2.500,0.000,NaN,NaN,NaN,NaN,NaN,NaN